version: 0.34.0-build{build}
skip_tags: true
image: Ubuntu1804
build_script:
  - sh: sudo bash appveyor-build.sh
test: off
on_failure:
  - 7z a -mx9 -r logs.7z *.log *.cmake *.ninja *.txt
  - appveyor PushArtifact log.7z
skip_commits:
  files:
    - "LICENSE"
    - "*.md"
    - ".gitingore"
